#!/bin/bash

echo '### wordpress google tag manager plugin by ivan shim'


cd ~shimclin/www/singapore/wp-content/plugins/is-google-tag-manager/


#echo "# is-menus" >> README.md
#git init
#git add README.md
#git commit -m "first commit"
#git branch -M master
#git remote add origin https://github.com/ivanshim/is-google-tag-manager.git
#git push -u origin master


git add .
git commit -m "`date`"
#git push -u origin master
git push -f -u origin master


