#!/bin/bash

echo '### wordpress google tag manager plugin by ivan shim'


cd ~shimclin/www/singapore/wp-content/plugins/zm-google-tag-manager/


#echo "# is-menus" >> README.md
#git init
#git add README.md
#git commit -m "first commit"
#git branch -M main
#git remote add origin https://github.com/zeusmicro/zm-google-tag-manager.git
#git push -u origin main


git add .
git commit -m "`date`"
git push -u origin main --force
#git push -f -u origin main


